// The source of src/components/fx/figures/Slots.tsx: the <Figure> component the pages use. One function, used both by the generator and by
// the project's own figure sync (scripts/lib/figures.mjs), so the two always write the same file.
//   <Figure place="signin" />     the figure chosen for a named place of the site (effects.figures)
//   <Figure name="padlock" />     any figure, anywhere in your own code

/**
 * @param {object} o
 * @param {string[]} o.places                 the places the site has (hero, signin, ...)
 * @param {Record<string,string>} o.chosen    place -> figure id
 * @param {string[]} [o.named]                figure ids used by name in the code
 * @param {number} [o.intensity]              0..1, how strongly figures answer the pointer
 */
export function slotsSource({ places, chosen = {}, named = [], intensity = 0.5 }) {
  const placeType = places.map((p) => `'${p}'`).join(' | ');
  const ids = [...new Set([...Object.values(chosen), ...named])].sort();
  if (!ids.length) {
    return [
      '// Generated by Sitewright: no figures are chosen, so every <Figure> renders nothing. Use one anywhere: <Figure name="padlock" /> (it is',
      '// brought in by `npm run dev` / `npm run build`), or choose them for the site\'s places with `scaffold.mjs --apply-effects --figures auto`.',
      `export type Place = ${placeType};`,
      '',
      'export function Figure(_: { place?: Place; name?: string; intensity?: number; className?: string }) {',
      '  return null;',
      '}',
      '',
    ].join('\n');
  }
  return [
    "'use client';",
    '',
    '// Generated by Sitewright (and kept in line with your code by `npm run dev` / `npm run build`). Interactive line figures from Hairline',
    '// (MIT, see figures/LICENSE-hairline.txt) and three of our own.',
    "import { useEffect, useLayoutEffect, useRef } from 'react';",
    "import type { Figure as Mounted, HairlineOptions } from './mount';",
    ...ids.map((id) => `import { ${id} } from './factories/${id}';`),
    '',
    `export type Place = ${placeType};`,
    'type Mount = (el: HTMLElement, options?: HairlineOptions) => Mounted;',
    '',
    '/** Which figure each place shows. Change a name here to change the figure. */',
    `const CHOSEN: Partial<Record<Place, Mount>> = { ${Object.entries(chosen).map(([place, id]) => `${place}: ${id}`).join(', ')} };`,
    '/** Every figure that can be used by name: <Figure name="padlock" />. */',
    `const NAMED: Record<string, Mount> = { ${ids.map((id) => `${id}`).join(', ')} };`,
    `const INTENSITY = ${intensity};`,
    '',
    "const useIsoLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect;",
    '',
    '/** An empty box on the server (so nothing shifts), the drawing once mounted. Nothing is drawn for a place or name with no figure. */',
    'export function Figure({ place, name, intensity, className }: { place?: Place; name?: string; intensity?: number; className?: string }) {',
    '  const mount = name ? NAMED[name] : place ? CHOSEN[place] : undefined;',
    '  const ref = useRef<HTMLDivElement>(null);',
    '  const strength = intensity ?? INTENSITY;',
    '  useIsoLayoutEffect(() => {',
    '    if (!mount || !ref.current) return;',
    '    const figure = mount(ref.current, { intensity: strength });',
    '    return () => figure.destroy();',
    '  }, [mount, strength]);',
    '  if (!mount) return null;',
    "  return <div ref={ref} className={`fx-fig fx-fig-${name ? 'named' : place}${className ? ` ${className}` : ''}`} />;",
    '}',
    '',
  ].join('\n');
}
