// Writes the effects layer of a generated project: the chosen component files, one fx.css, the slot file the pages import
// (index.tsx) and the micro-interaction attacher (micro.tsx). Called by scaffold.mjs when the 'fx' flag is set.

import fs from 'node:fs';
import path from 'node:path';
import { effectPlan, BACKGROUNDS, HEADLINES, BUTTONS, CARDS, REVEALS, EXTRAS, PRESETS } from '../effects.mjs';

const HEADLINE_FILES = {
  'split-chars': 'SplitChars', 'split-words': 'SplitWords', 'blur-in': 'BlurIn', typewriter: 'Typewriter',
  gradient: 'Gradient', shimmer: 'Shimmer', scramble: 'Scramble', rotate: 'Rotate',
};
const BACKGROUND_FILES = {
  aurora: 'Aurora', mesh: 'Mesh', dots: 'Dots', particles: 'Particles', stars: 'Stars',
  beams: 'Beams', waves: 'Waves', grid: 'Grid', grain: 'Grain', spotlight: 'Spotlight',
};
const CANVAS = new Set(['dots', 'particles', 'stars']);

/**
 * @param {object} o
 * @param {object} o.fx        resolved effects (resolveEffects)
 * @param {Set<string>} o.flags
 * @param {boolean} o.all      true for the gallery module: every effect is copied so the page can preview all of them
 * @param {string} o.templates path to the templates folder
 * @param {object} o.tokens    __TOKEN__ values
 * @param {(rel: string, content: string) => void} o.put
 * @param {(text: string, tokens: object, file: string) => string} o.fill
 */
export function generateFx({ fx, flags, all, templates, tokens, put, fill }) {
  const dir = path.join(templates, 'fx');
  const read = (rel) => fs.readFileSync(path.join(dir, rel), 'utf8').replace(/\r\n/g, '\n');
  const plan = effectPlan(fx, { all });

  // The shared canvas hook is only worth shipping when a canvas background is actually in use.
  const usesCanvas = all || CANVAS.has(fx.heroBackground) || CANVAS.has(fx.loginBackground);
  const files = plan.files.filter((f) => usesCanvas || f !== 'useCanvasLoop.ts');
  for (const rel of files) put(`src/components/fx/${rel}`, fill(read(rel), tokens, `fx/${rel}`));

  const css = plan.css.map((c) => `/* ${c} */\n${fill(read(`css/${c}.css`), tokens, `fx/css/${c}.css`)}`).join('\n');
  put('src/components/fx/fx.css',
    '/* Generated by Sitewright from the effects chosen in site.json. Every rule is scoped by a data-fx-* attribute or a class, so unused rules are inert. */\n' + css);

  // The slots the pages import. Swap a file name here to change an effect.
  const lines = [
    '// Generated by Sitewright. The slots the pages use: change which file a slot points at to change the effect.',
    "import type { Parts } from './text/split';",
    `import Chosen from './text/${HEADLINE_FILES[fx.headline] ?? 'Plain'}';`,
    fx.headline === 'rotate'
      ? `export function Headline(p: Parts) {\n  return <Chosen {...p} words={${JSON.stringify(fx.rotateWords)}} />;\n}`
      : 'export function Headline(p: Parts) {\n  return <Chosen {...p} />;\n}',
  ];
  if (flags.has('fx_bg')) lines.push(`export { default as HeroBackground } from './bg/${BACKGROUND_FILES[fx.heroBackground]}';`);
  if (flags.has('fx_login_bg')) lines.push(`export { default as LoginBackground } from './bg/${BACKGROUND_FILES[fx.loginBackground]}';`);
  if (flags.has('fx_countup')) lines.push("export { default as CountUp } from './CountUp';");
  put('src/components/fx/index.tsx', lines.join('\n') + '\n');

  // In the gallery the page-level extras are switched on and off by the playground itself, so only the button/card ones are global.
  const mods = all ? plan.micro.filter((m) => ['magnetic', 'ripple', 'tilt', 'spotlight'].includes(m)) : plan.micro;
  put('src/components/fx/micro.tsx', mods.length
    ? [
      "'use client';",
      '',
      "import { useEffect } from 'react';",
      ...mods.map((m) => `import { attach as ${m} } from './micro/${m}';`),
      '',
      '/** Attaches the chosen button, card and page-level micro-interactions once, and removes them on unmount. */',
      'export function FxMicro() {',
      '  useEffect(() => {',
      `    const offs = [${mods.map((m) => `${m}()`).join(', ')}];`,
      '    return () => offs.forEach((off) => off());',
      '  }, []);',
      '  return null;',
      '}',
      '',
    ].join('\n')
    : "'use client';\n\nexport function FxMicro() {\n  return null;\n}\n");

  if (all) put('src/components/fx/catalog.tsx', catalog());
}

const info = (table) => Object.entries(table).map(([id, e]) => ({ id, label: e.label, desc: e.desc }));
const ident = (id) => id.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''));

/** Everything the /effects playground needs: every component by id, plus the labels and presets from the registry. */
function catalog() {
  const bg = Object.keys(BACKGROUNDS);
  const hl = Object.keys(HEADLINES);
  const extraMicro = { 'cursor-glow': 'cursorGlow', 'scroll-progress': 'scrollProgress', 'click-spark': 'clickSpark' };
  const out = [
    '// Generated by Sitewright: every effect, by id, for the /effects playground.',
    "import type { ComponentType } from 'react';",
    "import type { Parts } from './text/split';",
    "import Plain from './text/Plain';",
    ...bg.map((id) => `import ${ident(id)}Bg from './bg/${BACKGROUND_FILES[id]}';`),
    ...hl.map((id) => `import ${ident(id)}Text from './text/${HEADLINE_FILES[id]}';`),
    ...Object.entries(extraMicro).map(([, m]) => `import { attach as ${m} } from './micro/${m}';`),
    "export { default as CountUp } from './CountUp';",
    '',
    `export const BACKGROUND_COMPONENTS: Record<string, ComponentType> = { ${bg.map((id) => `'${id}': ${ident(id)}Bg`).join(', ')} };`,
    `export const HEADLINE_COMPONENTS: Record<string, ComponentType<Parts & { words?: string[] }>> = { none: Plain, ${hl.map((id) => `'${id}': ${ident(id)}Text`).join(', ')} };`,
    `export const EXTRA_ATTACH: Record<string, () => () => void> = { ${Object.entries(extraMicro).map(([id, m]) => `'${id}': ${m}`).join(', ')} };`,
    `export const INFO = ${JSON.stringify({
      background: info(BACKGROUNDS), headline: info(HEADLINES), buttons: info(BUTTONS), cards: info(CARDS), reveal: info(REVEALS), extras: info(EXTRAS), presets: PRESETS,
    }, null, 2)} as const;`,
    '',
  ];
  return out.join('\n');
}
