// The brand mark. Every style keeps the two class names the landing page animates (.logo-hex draws itself in with a
// stroke-dash, .logo-lens pops in after it), so the original dashboard's draw-in works for any style.

export const LOGO_STYLES = ['hex', 'circle', 'square', 'drop', 'monogram'];

/** Inner SVG of the 48x48 mark. `ink`/`dot` are CSS colour expressions. */
function shapes(style, letter, ink, dot) {
  switch (style) {
    case 'circle':
      return `<circle className="logo-hex" pathLength={100} cx="24" cy="24" r="17.5" fill="none" stroke="${ink}" strokeWidth="5" />` +
        `<circle className="logo-lens" cx="24" cy="24" r="6.5" fill="${dot}" />`;
    case 'square':
      return `<rect className="logo-hex" pathLength={100} x="7.5" y="7.5" width="33" height="33" rx="9" fill="none" stroke="${ink}" strokeWidth="5" strokeLinejoin="round" />` +
        `<circle className="logo-lens" cx="24" cy="24" r="6.5" fill="${dot}" />`;
    case 'drop':
      return `<path className="logo-hex" pathLength={100} d="M24 5.5 C24 5.5 38 20 38 29.5 A14 14 0 0 1 10 29.5 C10 20 24 5.5 24 5.5 Z" fill="none" stroke="${ink}" strokeWidth="5" strokeLinejoin="round" />` +
        `<circle className="logo-lens" cx="24" cy="30" r="6" fill="${dot}" />`;
    case 'monogram':
      return `<rect className="logo-hex" pathLength={100} x="5" y="5" width="38" height="38" rx="11" fill="${ink}" stroke="${ink}" strokeWidth="2" strokeLinejoin="round" />` +
        `<text className="logo-lens" x="24" y="32.5" textAnchor="middle" fontSize="24" fontWeight="800" fontFamily="Montserrat, system-ui, sans-serif" fill="${dot}">${letter}</text>`;
    case 'hex':
    default:
      return `<path className="logo-hex" pathLength={100} d="M24 5.5 L40 14.75 V33.25 L24 42.5 L8 33.25 V14.75 Z" fill="none" stroke="${ink}" strokeWidth="5" strokeLinejoin="round" />` +
        `<circle className="logo-lens" cx="24" cy="24" r="6.5" fill="${dot}" />`;
  }
}

/** Brand names reach a block comment and JSX text: neither may be able to end its context. */
const commentSafe = (n) => String(n).replace(/[*/`$\\]/g, '');

export function logoComponent({ style, letter, name }) {
  const s = LOGO_STYLES.includes(style) ? style : 'hex';
  const inner = shapes(s, letter, 'var(--primary)', s === 'monogram' ? 'var(--on-primary)' : 'var(--signal)');
  return `/**
 * The ${commentSafe(name)} mark (style: ${s}). On the home page it draws itself in (\`animated\`); everywhere else it is static.
 * Generated by site-kit from site.json - change brand.logo there and re-run, or edit this file directly.
 */
export function LogoMark({ size = 30, animated = false, className = '' }: { size?: number; animated?: boolean; className?: string }) {
  return (
    <svg
      viewBox="0 0 48 48" width={size} height={size} aria-hidden="true"
      className={\`logo-mark\${animated ? ' draw' : ''}\${className ? \` \${className}\` : ''}\`}
    >
      ${inner}
    </svg>
  );
}

export function Wordmark({ sub }: { sub?: string }) {
  return (
    <span className="brand">
      <span className="brand-mark"><LogoMark /></span>
      <span className="brand-t">{${JSON.stringify(name)}}{sub ? <span> {sub}</span> : null}</span>
    </span>
  );
}
`;
}

/** Static SVG for app/icon.svg (the favicon): plain colours, no CSS variables. */
export function faviconSvg({ style, letter }, primary, signal, onPrimary) {
  const s = LOGO_STYLES.includes(style) ? style : 'hex';
  const raw = shapes(s, letter, primary, s === 'monogram' ? onPrimary : signal)
    .replace(/ className="[^"]*"/g, '').replace(/ pathLength=\{100\}/g, '')
    .replace(/strokeWidth/g, 'stroke-width').replace(/strokeLinejoin/g, 'stroke-linejoin')
    .replace(/textAnchor/g, 'text-anchor').replace(/fontSize/g, 'font-size').replace(/fontWeight/g, 'font-weight')
    .replace(/fontFamily/g, 'font-family');
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">${raw}</svg>\n`;
}
